/**
 * ValuePairsPage.tsx
 *
 * Full CRUD editor for DSpace submission form value-pair sets.
 *
 * Left panel  — list of all sets with pair count badges, search filter.
 * Right panel — inline pair editor: add / edit / delete / reorder pairs,
 *               plus set metadata (name, dc_term, note).
 *
 * Exports:
 *   ⬇ XML  — <form-value-pairs> snippet to embed in submission-forms.xml
 *   ⬇ TS   — SUBMISSION_VALUE_PAIRS constant for submission-value-pairs.tsx
 *
 * Seeding: run `python manage.py import_value_pairs` to populate from
 *          the existing submission-forms.xml.
 */

import { useCallback, useEffect,  useState } from "react";
import { apiFetch } from "../api/client";
import {
  Alert,
  EmptyState,
  FormGroup,
  LoadingBlock,
  Modal,
  ModalActions,
  PageHeader,
  Spinner,
  useNotice,
} from "../components/shared";

const BASE = "/api/dspace-config";

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

interface ValuePairSet {
  id: number;
  name: string;
  dc_term: string;
  note: string;
  pair_count: number;
  imported_at: string;
  updated_at: string;
  pairs?: ValuePair[];
}

interface ValuePair {
  id?: number;
  sort_order: number;
  displayed_value: string;
  stored_value: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// XML / TS export helpers (client-side preview)
// ─────────────────────────────────────────────────────────────────────────────

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function generateXml(sets: ValuePairSet[]): string {
  const lines = ['<?xml version="1.0" encoding="UTF-8"?>', "<form-value-pairs>"];
  for (const s of sets) {
    const dc = s.dc_term ? ` dc-term="${esc(s.dc_term)}"` : "";
    lines.push(`  <value-pairs value-pairs-name="${esc(s.name)}"${dc}>`);
    for (const p of s.pairs ?? []) {
      lines.push("    <pair>");
      lines.push(`      <displayed-value>${esc(p.displayed_value)}</displayed-value>`);
      lines.push(`      <stored-value>${esc(p.stored_value)}</stored-value>`);
      lines.push("    </pair>");
    }
    lines.push("  </value-pairs>");
  }
  lines.push("</form-value-pairs>");
  return lines.join("\n");
}

function generateTs(sets: ValuePairSet[]): string {
  const tsEsc = (s: string) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  const lines = [
    "// Auto-generated by DSpace CRIS Config Cockpit",
    "",
    "export type SubmissionValuePair = {",
    "  displayedValue?: string;",
    "  storedValue?: string;",
    "};",
    "",
    "export type SubmissionValuePairsConfig = {",
    "  name: string;",
    "  dcTerm?: string;",
    "  pairs: SubmissionValuePair[];",
    "};",
    "",
    "export const SUBMISSION_VALUE_PAIRS: Record<string, SubmissionValuePairsConfig> = {",
  ];
  sets.forEach((s, si) => {
    const comma = si < sets.length - 1 ? "," : "";
    lines.push(`  ${s.name}: {`);
    lines.push(`    name: "${tsEsc(s.name)}",`);
    if (s.dc_term) lines.push(`    dcTerm: "${tsEsc(s.dc_term)}",`);
    lines.push("    pairs: [");
    (s.pairs ?? []).forEach((p, pi) => {
      const pc = pi < (s.pairs?.length ?? 0) - 1 ? "," : "";
      lines.push(`      { displayedValue: "${tsEsc(p.displayed_value)}", storedValue: "${tsEsc(p.stored_value)}" }${pc}`);
    });
    lines.push("    ],");
    lines.push(`  }${comma}`);
  });
  lines.push("};", "", "export function getSubmissionValuePairs(name: string): SubmissionValuePairsConfig | undefined {",
    "  return SUBMISSION_VALUE_PAIRS[name];", "}");
  return lines.join("\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// ExportModal
// ─────────────────────────────────────────────────────────────────────────────

function ExportModal({ sets, format, onClose }: {
  sets: ValuePairSet[]; format: "xml" | "ts"; onClose: () => void;
}) {
  const [copied, setCopied] = useState(false);
  const content = format === "xml" ? generateXml(sets) : generateTs(sets);
  const filename = format === "xml" ? "submission-value-pairs.xml" : "submission-value-pairs.tsx";

  function copy() {
    navigator.clipboard.writeText(content).then(() => { setCopied(true); setTimeout(() => setCopied(false), 2000); });
  }
  function download() {
    const blob = new Blob([content], { type: format === "xml" ? "application/xml" : "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = filename;
    a.click();
    URL.revokeObjectURL(a.href);
  }

  return (
    <div style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.48)", zIndex: 2000,
      display: "flex", alignItems: "center", justifyContent: "center", padding: 24 }}
      onClick={onClose}>
      <div style={{ background: "#1e1e2e", borderRadius: 12, width: "100%", maxWidth: 800, maxHeight: "80vh",
        display: "flex", flexDirection: "column", boxShadow: "0 24px 80px rgba(0,0,0,0.4)" }}
        onClick={e => e.stopPropagation()}>
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between",
          padding: "13px 18px", borderBottom: "1px solid rgba(255,255,255,0.08)" }}>
          <div>
            <div style={{ fontSize: 13, fontWeight: 700, color: "#e2e8f0" }}>{filename}</div>
            <div style={{ fontSize: 11, color: "#64748b", marginTop: 2 }}>
              {sets.length} sets · {sets.reduce((s, x) => s + (x.pairs?.length ?? 0), 0)} total pairs
            </div>
          </div>
          <div style={{ display: "flex", gap: 8 }}>
            <button onClick={download} style={{ padding: "5px 13px", borderRadius: 6, border: "none",
              background: "#059669", color: "#fff", fontSize: 12, fontWeight: 600, cursor: "pointer" }}>
              ⬇ Download
            </button>
            <button onClick={copy} style={{ padding: "5px 13px", borderRadius: 6, border: "none",
              background: copied ? "#22c55e" : "#4f46e5", color: "#fff", fontSize: 12, fontWeight: 600, cursor: "pointer" }}>
              {copied ? "✓ Copied!" : "Copy"}
            </button>
            <button onClick={onClose} style={{ padding: "5px 10px", borderRadius: 6,
              border: "1px solid rgba(255,255,255,0.12)", background: "transparent",
              color: "#94a3b8", fontSize: 13, cursor: "pointer" }}>✕</button>
          </div>
        </div>
        <pre style={{ flex: 1, overflowY: "auto", margin: 0, padding: "14px 18px",
          fontFamily: "'JetBrains Mono','Fira Code',monospace", fontSize: 11.5, lineHeight: 1.6,
          color: format === "xml" ? "#a5f3fc" : "#bbf7d0", background: "transparent",
          whiteSpace: "pre-wrap", wordBreak: "break-all" }}>
          {content}
        </pre>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// PairRow — single editable row in the pair editor
// ─────────────────────────────────────────────────────────────────────────────

function PairRow({ pair, idx, total, onChange, onDelete, onMove }: {
  pair: ValuePair; idx: number; total: number;
  onChange: (patch: Partial<ValuePair>) => void;
  onDelete: () => void;
  onMove: (dir: "up" | "down") => void;
}) {
  return (
    <tr>
      <td style={{ paddingRight: 4, color: "var(--muted)", fontSize: 11, width: 32, textAlign: "center" }}>
        {idx + 1}
      </td>
      <td style={{ paddingRight: 6 }}>
        <input
          value={pair.displayed_value}
          onChange={e => onChange({ displayed_value: e.target.value })}
          placeholder="Displayed label"
          style={{ width: "100%", padding: "4px 7px", fontSize: 12,
            border: "1px solid var(--border)", borderRadius: 5, outline: "none" }}
        />
      </td>
      <td style={{ paddingRight: 6 }}>
        <input
          value={pair.stored_value}
          onChange={e => onChange({ stored_value: e.target.value })}
          placeholder="Stored value"
          style={{ width: "100%", padding: "4px 7px", fontSize: 12, fontFamily: "monospace",
            border: "1px solid var(--border)", borderRadius: 5, outline: "none" }}
        />
      </td>
      <td style={{ whiteSpace: "nowrap" }}>
        <div style={{ display: "flex", gap: 3 }}>
          <button onClick={() => onMove("up")} disabled={idx === 0}
            className="btn btn-sm" style={{ padding: "3px 7px", minWidth: 0 }}
            title="Move up">↑</button>
          <button onClick={() => onMove("down")} disabled={idx === total - 1}
            className="btn btn-sm" style={{ padding: "3px 7px", minWidth: 0 }}
            title="Move down">↓</button>
          <button onClick={onDelete}
            className="btn btn-sm btn-danger" style={{ padding: "3px 7px", minWidth: 0 }}
            title="Remove pair">✕</button>
        </div>
      </td>
    </tr>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// SetEditor — right-panel editor for a single selected set
// ─────────────────────────────────────────────────────────────────────────────

function SetEditor({ set, onSaved, onDeleted }: {
  set: ValuePairSet;
  onSaved: (updated: ValuePairSet) => void;
  onDeleted: () => void;
}) {
  const [name,    setName]    = useState(set.name);
  const [dcTerm,  setDcTerm]  = useState(set.dc_term);
  const [note,    setNote]    = useState(set.note);
  const [pairs,   setPairs]   = useState<ValuePair[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving,  setSaving]  = useState(false);
  const [dirty,   setDirty]   = useState(false);
  const { notice, notify } = useNotice();

  // Load full pairs when set changes
  useEffect(() => {
    setLoading(true);
    setDirty(false);
    setName(set.name);
    setDcTerm(set.dc_term);
    setNote(set.note);
    apiFetch<ValuePairSet>(`${BASE}/value-pair-sets/${set.id}/`)
      .then(d => { setPairs(d.pairs ?? []); })
      .catch(() => notify("error", "Failed to load pairs."))
      .finally(() => setLoading(false));
  }, [set.id]); // eslint-disable-line

  function mark() { setDirty(true); }

  function addPair() {
    setPairs(prev => [...prev, { sort_order: prev.length, displayed_value: "", stored_value: "" }]);
    mark();
  }

  function updatePair(idx: number, patch: Partial<ValuePair>) {
    setPairs(prev => prev.map((p, i) => i === idx ? { ...p, ...patch } : p));
    mark();
  }

  function deletePair(idx: number) {
    setPairs(prev => prev.filter((_, i) => i !== idx).map((p, i) => ({ ...p, sort_order: i })));
    mark();
  }

  function movePair(idx: number, dir: "up" | "down") {
    const ni = dir === "up" ? idx - 1 : idx + 1;
    if (ni < 0 || ni >= pairs.length) return;
    setPairs(prev => {
      const arr = [...prev];
      [arr[idx], arr[ni]] = [arr[ni], arr[idx]];
      return arr.map((p, i) => ({ ...p, sort_order: i }));
    });
    mark();
  }

  async function save() {
    setSaving(true);
    try {
      // 1. Update set metadata
      await apiFetch(`${BASE}/value-pair-sets/${set.id}/`, {
        method: "PATCH",
        body: { name, dc_term: dcTerm, note },
      });
      // 2. Replace all pairs atomically
      const updated = await apiFetch<ValuePairSet>(
        `${BASE}/value-pair-sets/${set.id}/replace-pairs/`,
        { method: "POST", body: { pairs: pairs.map(p => ({ displayed_value: p.displayed_value, stored_value: p.stored_value })) } }
      );
      setPairs(updated.pairs ?? []);
      setDirty(false);
      notify("success", "Saved.");
      onSaved({ ...updated, name, dc_term: dcTerm, note });
    } catch (e: any) {
      notify("error", e?.detail ?? "Save failed.");
    } finally {
      setSaving(false);
    }
  }

  async function deleteSet() {
    if (!confirm(`Delete value-pair set "${set.name}" and all its ${pairs.length} pairs?`)) return;
    try {
      await apiFetch(`${BASE}/value-pair-sets/${set.id}/`, { method: "DELETE" });
      onDeleted();
    } catch {
      notify("error", "Delete failed.");
    }
  }

  return (
    <div style={{ display: "flex", flexDirection: "column", height: "100%" }}>
      {/* Editor toolbar */}
      <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 12, flexWrap: "wrap" }}>
        <div className="card-title" style={{ margin: 0, flex: 1 }}>
          <code style={{ fontSize: 14 }}>{set.name}</code>
          <span className="count-badge" style={{ marginLeft: 8 }}>{pairs.length} pairs</span>
          {dirty && <span style={{ marginLeft: 8, fontSize: 11, color: "#f59e0b" }}>● unsaved</span>}
        </div>
        <button className="btn btn-sm btn-danger" onClick={deleteSet}>Delete set</button>
        <button className="btn btn-sm btn-primary" onClick={save} disabled={saving || !dirty}>
          {saving ? <><Spinner white /> Saving…</> : "💾 Save"}
        </button>
      </div>

      {notice && <Alert type={notice.type} onDismiss={() => {}}>{notice.msg}</Alert>}

      {/* Set metadata */}
      <div className="card" style={{ marginBottom: 12, padding: "12px 14px" }}>
        <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
          <FormGroup label="Set name (value-pairs-name)" hint="Used in input-type value-pairs-name= attribute">
            <input value={name} onChange={e => { setName(e.target.value); mark(); }}
              style={{ fontFamily: "monospace" }} />
          </FormGroup>
          <FormGroup label="dc-term" hint="dc-term attribute in submission-forms.xml">
            <input value={dcTerm} onChange={e => { setDcTerm(e.target.value); mark(); }} />
          </FormGroup>
        </div>
        <FormGroup label="Note (optional)">
          <textarea value={note} onChange={e => { setNote(e.target.value); mark(); }}
            rows={2} style={{ resize: "vertical" }} />
        </FormGroup>
      </div>

      {/* Pairs table */}
      <div className="card" style={{ flex: 1, overflow: "hidden", display: "flex", flexDirection: "column" }}>
        <div style={{ display: "flex", alignItems: "center", marginBottom: 10 }}>
          <span className="card-title" style={{ margin: 0, flex: 1 }}>Pairs</span>
          <button className="btn btn-sm btn-primary" onClick={addPair}>+ Add pair</button>
        </div>
        {loading ? <LoadingBlock label="Loading pairs…" /> : (
          <div style={{ flex: 1, overflowY: "auto" }}>
            {pairs.length === 0 ? (
              <EmptyState msg="No pairs yet. Click '+ Add pair' to start." />
            ) : (
              <table style={{ width: "100%", borderCollapse: "collapse" }}>
                <thead>
                  <tr style={{ borderBottom: "2px solid var(--border)" }}>
                    <th style={{ width: 32, padding: "5px 4px", fontSize: 11, color: "var(--muted)" }}>#</th>
                    <th style={{ textAlign: "left", padding: "5px 6px 5px 0", fontSize: 11,
                      fontWeight: 600, color: "var(--muted)", textTransform: "uppercase" }}>Displayed value</th>
                    <th style={{ textAlign: "left", padding: "5px 6px 5px 0", fontSize: 11,
                      fontWeight: 600, color: "var(--muted)", textTransform: "uppercase" }}>Stored value</th>
                    <th style={{ width: 110 }}></th>
                  </tr>
                </thead>
                <tbody>
                  {pairs.map((pair, idx) => (
                    <PairRow key={idx} pair={pair} idx={idx} total={pairs.length}
                      onChange={patch => updatePair(idx, patch)}
                      onDelete={() => deletePair(idx)}
                      onMove={dir => movePair(idx, dir)}
                    />
                  ))}
                </tbody>
              </table>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// ValuePairsPage — main exported page
// ─────────────────────────────────────────────────────────────────────────────

export function ValuePairsPage() {
  const [sets,       setSets]       = useState<ValuePairSet[]>([]);
  const [loading,    setLoading]    = useState(true);
  const [selected,   setSelected]   = useState<ValuePairSet | null>(null);
  const [search,     setSearch]     = useState("");
  const [modal,      setModal]      = useState<"new" | "xml" | "ts" | null>(null);
  const [newName,    setNewName]    = useState("");
  const [newDcTerm,  setNewDcTerm]  = useState("");
  const [creating,   setCreating]   = useState(false);
  // For export modals we need all sets with pairs loaded
  const [allWithPairs, setAllWithPairs] = useState<ValuePairSet[]>([]);
  const [loadingAll,   setLoadingAll]   = useState(false);
  const { notice, notify } = useNotice();

  const load = useCallback(async () => {
    try {
      const data = await apiFetch<ValuePairSet[]>(`${BASE}/value-pair-sets/`);
      setSets(data);
      if (selected) setSelected(data.find(s => s.id === selected.id) ?? null);
    } catch { notify("error", "Failed to load value-pair sets."); }
    finally { setLoading(false); }
  }, [selected]); // eslint-disable-line

  useEffect(() => { load(); }, []); // eslint-disable-line

  async function loadAllWithPairs() {
    setLoadingAll(true);
    try {
      const list = await apiFetch<ValuePairSet[]>(`${BASE}/value-pair-sets/`);
      const full = await Promise.all(
        list.map(s => apiFetch<ValuePairSet>(`${BASE}/value-pair-sets/${s.id}/`))
      );
      setAllWithPairs(full);
    } catch { notify("error", "Failed to load sets for export."); }
    finally { setLoadingAll(false); }
  }

  async function openExport(fmt: "xml" | "ts") {
    await loadAllWithPairs();
    setModal(fmt);
  }

  async function createSet() {
    if (!newName.trim()) return;
    setCreating(true);
    try {
      const created = await apiFetch<ValuePairSet>(`${BASE}/value-pair-sets/`, {
        method: "POST",
        body: { name: newName.trim(), dc_term: newDcTerm.trim(), note: "" },
      });
      notify("success", `Set "${created.name}" created.`);
      setNewName(""); setNewDcTerm("");
      setModal(null);
      await load();
      setSelected(created);
    } catch (e: any) {
      notify("error", e?.detail ?? "Create failed.");
    } finally {
      setCreating(false);
    }
  }

  const filtered = sets.filter(s =>
    s.name.toLowerCase().includes(search.toLowerCase()) ||
    s.dc_term.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div>
      <PageHeader
        title="Value Pairs"
        desc="Manage the dropdown option lists used in DSpace submission forms. Seed from submission-forms.xml, edit here, export back to XML or TypeScript."
        actions={
          <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
            <button className="btn" onClick={() => openExport("xml")} disabled={loadingAll}>
              {loadingAll ? <Spinner /> : "⬇ XML"}
            </button>
            <button className="btn" onClick={() => openExport("ts")} disabled={loadingAll}>
              {loadingAll ? <Spinner /> : "⬇ TypeScript"}
            </button>
            <button className="btn btn-primary" onClick={() => setModal("new")}>
              + New Set
            </button>
          </div>
        }
      />

      {notice && <Alert type={notice.type}>{notice.msg}</Alert>}

      <div className="two-col">
        {/* LEFT — set list */}
        <div className="card">
          <div style={{ display: "flex", alignItems: "center", marginBottom: 12 }}>
            <div className="card-title" style={{ margin: 0, flex: 1 }}>
              Sets <span className="count-badge">{sets.length}</span>
            </div>
            <input value={search} onChange={e => setSearch(e.target.value)}
              placeholder="Filter sets…"
              style={{ width: 160, padding: "5px 9px", fontSize: 12,
                border: "1px solid var(--border)", borderRadius: 6, outline: "none" }} />
          </div>

          {loading ? <LoadingBlock /> : filtered.length === 0 ? (
            <EmptyState msg={sets.length === 0
              ? "No value-pair sets yet. Run 'python manage.py import_value_pairs' to seed from submission-forms.xml, or create a new set manually."
              : "No sets match your search."} />
          ) : (
            filtered.map(s => (
              <div
                key={s.id}
                className={`preset-item${selected?.id === s.id ? " selected" : ""}`}
                onClick={() => setSelected(s)}
              >
                <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 8 }}>
                  <div style={{ minWidth: 0 }}>
                    <div style={{ fontWeight: 700, fontSize: 13, fontFamily: "monospace", color: "var(--accent)" }}>
                      {s.name}
                    </div>
                    {s.dc_term && (
                      <div style={{ fontSize: 11, color: "var(--muted)", marginTop: 1 }}>
                        dc-term: <code>{s.dc_term}</code>
                      </div>
                    )}
                  </div>
                  <span className="count-badge" style={{ flexShrink: 0 }}>{s.pair_count}</span>
                </div>
                {s.note && (
                  <div style={{ fontSize: 11, color: "var(--muted)", marginTop: 4 }}>{s.note}</div>
                )}
              </div>
            ))
          )}
        </div>

        {/* RIGHT — set editor */}
        <div style={{ minWidth: 0 }}>
          {selected ? (
            <SetEditor
              key={selected.id}
              set={selected}
              onSaved={updated => {
                setSets(prev => prev.map(s => s.id === updated.id ? { ...s, ...updated, pair_count: updated.pairs?.length ?? s.pair_count } : s));
                setSelected({ ...selected, ...updated });
              }}
              onDeleted={() => {
                setSets(prev => prev.filter(s => s.id !== selected.id));
                setSelected(null);
                notify("success", "Set deleted.");
              }}
            />
          ) : (
            <div className="card">
              <EmptyState msg="← Select a value-pair set to edit its options." />
            </div>
          )}
        </div>
      </div>

      {/* New set modal */}
      {modal === "new" && (
        <Modal title="New Value-Pair Set" onClose={() => setModal(null)}>
          <FormGroup label="Set name (value-pairs-name)" hint='e.g. "common_iso_languages" — must match the name used in submission-forms.xml fields'>
            <input value={newName} onChange={e => setNewName(e.target.value)}
              onKeyDown={e => e.key === "Enter" && createSet()}
              placeholder="e.g. my_custom_types"
              style={{ fontFamily: "monospace" }}
              autoFocus />
          </FormGroup>
          <FormGroup label="dc-term (optional)" hint="The dc-term attribute in submission-forms.xml — often the same as the set name">
            <input value={newDcTerm} onChange={e => setNewDcTerm(e.target.value)}
              placeholder="e.g. my_custom_types" />
          </FormGroup>
          <ModalActions>
            <button className="btn" onClick={() => setModal(null)} disabled={creating}>Cancel</button>
            <button className="btn btn-primary" onClick={createSet} disabled={creating || !newName.trim()}>
              {creating ? <><Spinner white /> Creating…</> : "Create"}
            </button>
          </ModalActions>
        </Modal>
      )}

      {/* Export modals */}
      {(modal === "xml" || modal === "ts") && (
        <ExportModal
          sets={allWithPairs}
          format={modal}
          onClose={() => setModal(null)}
        />
      )}
    </div>
  );
}
